version: '3.8'
services:
  app:
    restart: unless-stopped
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node_network
      
  web:
    restart: unless-stopped
    build: ./web
    ports:
      - 8080:443
      - 8081:80
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/ssl/server.key:/etc/nginx/server.key
      - ./web/ssl/server.crt:/etc/nginx/server.crt
    networks:
      - node_network

networks:
  node_network:
